### ISSUE TITLE
Design Docs To Do List

### ISSUE THREAD

**Issue by mwmadsen67** [jgerville/Facenook#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Hi Julian, nice job on your design docs so far! I just have a few notes/questions.

Schema:
- For friend requests, I'm concerned that checking if requests exist in both directions is not the most optimal way of handling requests. It might be better to have a boolean column on a friend_req that says whether or not the request was accepted.
- For posts, I can see that each one has a wall_id which I assume is for figuring out which posts on on different users walls, but how do you plan on having posts on the general news feed?
- Everything else in the schema looks good and is nicely formatted, nice work.

State Shape:
- Most of the keys have underscores, they should be camelcase
- otherwise looks good

**Comment by mwmadsen67** [comment]
Also dont forget to do your MVP List!

**Comment by jgerville** [comment]
Thanks for the feedback. The boolean idea for friend requests makes sense; I'll just turn accepting a friend request into a `PATCH` request.

My idea with walls and the newsfeed is that if a user wants to post something, they can either post it on their own wall, or on a friend's wall. So, when visiting someone else's wall, you'll only see posts that have the corresponding wall_id. For a user's own newsfeed, they will be shown any posts that were posted onto their wall or one of their friends' walls.

I'll also fix the state shape keys!

**Comment by jgerville** [comment]
Okay, I've updated all of the docs and added an MVP list!

**Comment by mwmadsen67** [comment]
Sweet, thanks Julian. 
Ok, it doesn't really sound like a newsfeed then since users essentially have to visit each others walls to see other posts. Since the newsfeed is not one of your MVPs, that's ok.

**Comment by mwmadsen67** [comment]
Alright feel free to make changes to the friend_req table if you want to after our talk today. Otherwise the schema looks good. 👍 

State looks good 👍 

MVP List looks good 👍 

Frontend Routes:
- nice job planning out these routes
- what is the difference between the ProfPic in the PostHeader and in the SmallUserCard?

Backend Routes:
- I'm curious on what you plan on doing with the users index route, I have a feeling you may not need it however
- Looking ahead at the posts, it may be easier to have a user show route that handles the request when visiting a users facebook page. In one request you could use their id to get that users info as well as all associated posts and friends. This may be easier than dealing with two types of post index requests.
- you may not need the friend req index route, typically that info will come from other other requests.

**Comment by jgerville** [comment]
Thanks for the feedback, I'll add a user show route for when users visit another user's profile page!
